GET http://localhost:3000/api/login HTTP/1.1

###

POST http://localhost:3000/api/echo HTTP/1.1
content-type: application/json

{
    "title":"title", 
    "status":"active", 
    "teacher_id":2,
    "year":2025
}